wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.45.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725000874
    t:
      1:
      - 1
      - 11
      - 33
      - 47
      - 49
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 33
      - 47
      - 49
      - 53
      - 55
      - 71
      - 105
      3:
      - 1
      - 23
      4: 3.10.14
      5: 0.17.0
      6: 4.45.0.dev0
      8:
      - 5
      13: linux-x86_64
